### ISSUE TITLE
can`t even run

### ISSUE THREAD

**Issue by say1j** [Daniele122898/StatusPage#2]
Your API throw an exception: System.NullReferenceException: "Object reference not set to an instance of an object."
authSettings was null.
at next string: JwtKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes(authSettings.Token));
Rename appsettings example to appsettings gives next:
"IDX10703: Cannot create a '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]', key length is zero."
Random values in Auth gives next:
An unhandled exception occurred while processing the request.
FileNotFoundException: Could not find file 'D:\StatusPage-master\StatusPageAPI\StatusPageAPI\wwwroot\index.html'.
In your angular after creating component (ng generate component Checker-Status) http://localhost:4200/ still empty.
Can u give some tips/advices how to make it work?
So interesting in your staff and wanna test it out
![image](https://user-images.githubusercontent.com/31889581/96365163-4735f200-1147-11eb-946c-4ca42b218c9e.png)

**Comment by Daniele122898** [comment]
Hey,

You must have a token in your appsettings.json. That is used to generate the jwt token. Also a username and password have to be set and the token issuer should be the url to the backend. So if you host it all in one it should be `http://localhost:5000/`. 

The Frontend is configured in a way such that when you use `ng build --prod` it will build angular for production and copy those files into the folder `../StatusPageAPI/StatusPageAPI/wwwroot`. So if you didnt change any paths it should copy the output to the wwwroot folder. Maybe try to create that folder manually and then re-compile the FE again. 

Hope that helps. 

Edit: I have added some additional information to the readme. Hope that helps you on the way

**Comment by say1j** [comment]
ty

**Comment by Daniele122898** [comment]
is everything working now?
